name: test workflows

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: CD
    steps:
      - name: load repo
        id: load-repo
        uses: actions/checkout@v2
      - name: run index js
        id: run-index-js
        uses: AHBruns/actions@v5
